### ISSUE TITLE
Library not found for -lX11

### ISSUE THREAD

**Issue by nicofirst1** [nikp123/xava#6] opened 2019-11-05 09:58 UTC
I am trying to make xava work on my mac, but with no success.

### OS:
```
System Software Overview:

      System Version: macOS 10.15.1 (19B88)
      Kernel Version: Darwin 19.0.0

```

### Steps:
I cloned the repo from git and used the following cmake commands:

`cmake  .. -DCMAKE_BUILD_TYPE=Release`

But I got the following warning:

`X11 and/or Xfixes library not found`

I stumbled upon [this stack question](https://stackoverflow.com/questions/11465258/xlib-h-not-found-when-building-graphviz-on-mac-os-x-10-8-mountain-lion) and did the following:
- `xcode-select --install `
- `ln -s /opt/X11/include/X11 /usr/local/include/X11`
- 'export CPPFLAGS=-I/opt/X11/include' 

With no success.

**Comment by nikp123** [comment] 2019-11-05 12:54
[CMakeLists.txt](https://github.com/nikp123/xava/files/3809025/CMakeLists.txt)
try this CMakeLists

pkg-config is broken anyway on anything that isn't Linux, so I might just switch back for the sake of portability

**Comment by nicofirst1** [comment] 2019-11-05 13:06
I used the CMakeLists.txt you provided and now I get this when using `make`:
```
Undefined symbols for architecture x86_64:
  "_glXSwapIntervalEXT", referenced from:
      _apply_window_settings_x in graphical_x.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [xava] Error 1
make[1]: *** [CMakeFiles/xava.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by nikp123** [comment] 2019-11-05 13:14
[CMakeLists.txt](https://github.com/nikp123/xava/files/3809087/CMakeLists.txt)
This CMake disables OpenGL in X11 (aka GLX) for macOS,
since it seems with a quick search that GLX is NOT supported in macOS.
Possibly may be resolved by implementing a native macOS window, but for now you can just do without macOS.

**Comment by nicofirst1** [comment] 2019-11-05 13:18
Whit this last CMakeLists.txt I am able to `make`, but I get the same error as before when running _xava_:
```
xava was built without Xlib support, install Xlib dev files
and run make clean && ./configure && make again
```

**Comment by nikp123** [comment] 2019-11-05 13:21
clear the build folder, this seems to be a cache issue @nicofirst1

**Comment by nicofirst1** [comment] 2019-11-05 13:28
Sorry my bad, I used `make install` previously and now I can run it, but the output is this:
```
Vsync works only when OpenGL is present!
W: [] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
Could not open pulseaudio mainloop to find default device name: 0
check if pulseaudio is running
```
Which is fine since I still need to download pulseaudio

**Comment by nicofirst1** [comment] 2019-11-05 13:33
Ok with pulseaudio running I get this when executing xava:
```
Vsync works only when OpenGL is present!
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  78 (X_CreateColormap)
  Serial number of failed request:  7
  Current serial number in output stream:  8
```

**Comment by nikp123** [comment] 2019-11-05 13:47
use portaudio as its supported by macOS natively
for that other issue its not audio related, its X11 erroring out, also do you have XQuartz installed?

**Comment by nikp123** [comment] 2019-11-05 13:59
also try disabling transparency

**Comment by nicofirst1** [comment] 2019-11-05 14:19
I do have XQuartz installed, using portaudio XQuartz starts and then I get the same error as before:
```
Vsync works only when OpenGL is present!
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  78 (X_CreateColormap)
  Serial number of failed request:  7
  Current serial number in output stream:  8
```
Disabling the transparency did not help

**Comment by nikp123** [comment] 2020-08-20 16:36
inb4 I need a ARM Mac now... thanks Apple :+1:

**Comment by nikp123** [comment] 2020-09-21 14:14
CMake's FindX11 helps here. Just need a system to test on :(

**Comment by nikp123** [comment] 2020-10-08 12:06
Fixed X11 and it's confirmed working on my hackintosh. Try it yourself once you build.

Steps after building: copy the example_files/config into ``/Users/username/.config/xava/config`` and disable transparency (because XQuartz doesnt work with it)

**Comment by nikp123** [comment] 2020-10-08 12:07
Its turns out to be a pkg-config issue, you cant do really anything around it except provide a patch like I just did

**Comment by TechAdvancedCyborg** [comment] 2020-10-15 17:57
@nikp123 Do you have a list of the different dependencies to install on MacOS? I have homebrew.

**Comment by TechAdvancedCyborg** [comment] 2020-10-15 18:03
Because right now it can't find iniparser even though I have installed it via homebrew and cloned the submodule.

**Comment by TechAdvancedCyborg** [comment] 2020-10-15 18:12
if you can just send me a compiled version, that would be much easier to test. (on a MacBook Pro (Retina, 15-inch, Mid 2015))

**Comment by nikp123** [comment] 2020-10-15 21:55
@TechAdvancedCyborg 
iniparser is automatically resolved, DO NOT install it on your own. This is because not all package managers ship it by default. Please allow cmake to resolve for itself, if it does not work, then please paste the log here. But what I'm guessing is that you're probably missing ``git`` as a dependency.

**Comment by nikp123** [comment] 2020-10-15 21:57
Also I'm going to send a guide in the README. I'll mostly use ``brew`` as other macOS package managers are inconsistent af and just cause trouble on my end it seems.

**Comment by nikp123** [comment] 2020-10-15 21:58
Just busy atm, second year of IBDP :(

**Comment by satyrnhub** [comment] 2021-01-16 05:28
> Also I'm going to write a guide in the README. I'll mostly use `brew` as other macOS package managers are inconsistent af and just cause trouble on my end it seems.

Any update on this? @nikp123

**Comment by nikp123** [comment] 2021-01-16 08:41
@satyrnhub Look now, I added the necessary info to README.

**Comment by satyrnhub** [comment] 2021-01-16 16:08
> @satyrnhub Look now, I added the necessary info to README.

Cool, thanks!

**Comment by satyrnhub** [comment] 2021-01-16 16:10
> @satyrnhub Look now, I added the necessary info to README.

New issue found. `ld: library not found for -lportaudio` @nikp123 Not sure if this is already a known issue, sorry if it is.

**Comment by nikp123** [comment] 2021-01-16 16:36
@satyrnhub Are you absolutely sure you have portaudio installed. Maybe the package I listed was wrong.. Do a ``brew search`` and find it, as I no longer have a Mac.

**Comment by satyrnhub** [comment] 2021-01-16 16:47
> @satyrnhub Are you absolutely sure you have portaudio installed. Maybe the package I listed was wrong.. Do a `brew search` and find it, as I no longer have a Mac.

Yup, 100% know it's installed.

**Comment by satyrnhub** [comment] 2021-01-16 16:47
@nikp123 I've tried the main version and the --HEAD version. The --HEAD version gives me tons of syntax errors on compiling.

**Comment by nikp123** [comment] 2021-01-16 17:37
@styarnhub Try something like this: https://apple.stackexchange.com/questions/145437/where-can-i-find-the-installed-package-path-via-brew
Or even try changing the pkg-config path to point to the brew's own pkg-config.

I'm sorry for giving vague advice, since I no longer have a machine for testing. Don't expect this to work.

**Comment by satyrnhub** [comment] 2021-01-16 18:26
> @styarnhub Try something like this: https://apple.stackexchange.com/questions/145437/where-can-i-find-the-installed-package-path-via-brew
> Or even try changing the pkg-config path to point to the brew's own pkg-config.
> 
> I'm sorry for giving vague advice, since I no longer have a machine for testing. Don't expect this to work.

I tried compiling the 0.6.3.1 version instead of the latest commit: `[ 36%] Building C object CMakeFiles/xava.dir/src/shared.c.o
/Users/<real name here>/Downloads/xava/src/shared.c:32:13: error: use of undeclared identifier 'MAX_PATH'
        char _path[MAX_PATH];`

**Comment by nikp123** [comment] 2021-01-16 21:33
just as a hack replace it with ``PATH_MAX`` to get it to build
I'll look into it later

**Comment by satyrnhub** [comment] 2021-01-16 23:11
> just as a hack replace it with `PATH_MAX` to get it to build
> I'll look into it later

Fixed building `shared.c`:
Add this to line 22 on 0.6.3.1 (from latest version):
`#ifdef __APPLE__
	#include <sys/syslimits.h>
	#define MAX_PATH PATH_MAX 
#endif`

Now having issues with SDL2, so I'm installing the latest commit version.

**Comment by nikp123** [comment] 2021-01-16 23:14
Most likely a pkg-config issue, will have to look into that.

Try changing the pkg-config path as I've suggestion before...
Or even change the pkg-config binary being passed to CMake.

**Comment by satyrnhub** [comment] 2021-01-16 23:29
> Most likely a pkg-config issue, will have to look into that.
> 
> Try changing the pkg-config path as I've suggestion before...
> Or even change the pkg-config binary being passed to CMake.

Sorry, I'm new to all this, how exactly would I do that?

**Comment by nikp123** [comment] 2021-01-16 23:50
Set ``PKG_CONFIG_PATH`` to the pkg-config binary you find in ``/usr/local/``.

**Comment by satyrnhub** [comment] 2021-01-16 23:53
> Set `PKG_CONFIG_PATH` to the pkg-config binary you find in `/usr/local/`.

Didn't work...

**Comment by nikp123** [comment] 2021-01-16 23:58
dunno, will have to look in later

**Comment by satyrnhub** [comment] 2021-01-17 03:22
> dunno, will have to look in later

Made a fork, look at the `macos` branch. That fixes compiling, but when `xava` is run, no output is displayed. I have the latest XQuartz alpha installed.

**Comment by satyrnhub** [comment] 2021-01-17 04:11
> > dunno, will have to look in later
> 
> Made a fork, look at the `macos` branch. That fixes compiling, but when `xava` is run, no output is displayed. I have the latest XQuartz alpha installed. @nikp123

Appears to be an XQuartz problem!

**Comment by nikp123** [comment] 2021-01-17 18:43
On an unrelated note, just managed to get an old MacBook Air for testing and the whole LD_LIBRARY shenanigan isn't necessary. Please verify by clearing the build folder and trying to build again.

**Comment by nikp123** [comment] 2021-01-17 18:48
Sorry I meant the LIBRARY_PATH thing. My mistake.

**Comment by satyrnhub** [comment] 2021-01-17 19:16
> On an unrelated note, just managed to get an old MacBook Air for testing and the whole LD_LIBRARY shenanigan isn't necessary. Please verify by clearing the build folder and trying to build again.

@nikp123 Still won't compile without it. Maybe specify that it might be needed depending on the system?

**Comment by nikp123** [comment] 2021-01-17 19:20
No need. It doesnt hinder the compilation process on my system, keep it as is.

**Comment by nikp123** [comment] 2021-01-17 19:21
Closing as this sorted out entirely now.

**Closed** 2021-01-17 19:21 UTC
Labels: bug, help wanted
