### ISSUE TITLE
[i3] correctly sits under floating windows, but over tiled windows

### ISSUE THREAD

**Issue by xdrie** [nikp123/xava#18] opened 2020-06-07 05:02 UTC
![image](https://user-images.githubusercontent.com/54390138/83960749-2bd5e480-a841-11ea-94b4-0592690eb20a.png)

XAVA correctly stays in the background of floating windows, but still draws over tiled windows.

perhaps something like Conky setting override redirect will work? https://faq.i3wm.org/question/3829/conky-on-desktop.1.html

my config: 
[xava_config.txt](https://github.com/nikp123/xava/files/4741409/xava_config.txt)

**Comment by nikp123** [comment] 2020-06-07 13:36
I'm going to guess that you want the visualizer to be behind all windows (be it floating or tiling). The problem is that i3 doesn't allow for floating windows (XAVA) to be behind tiling ones, no matter what rules you give it.

You can try making the window tiling, but that would be a waste of desktop space I assume.

However, I've made a workaround (since X11 spec technically doesn't encourage this) that works ONLY if you disable compositing altogether (so no compton, xcompmgr, compiz...). It's ``rootwindow`` and it does exactly what it says, XAVA uses the root window for it's graphics - a root window being your desktop (or desktop wallpaper). And by enabling this you could allow XAVA to draw behind tiling windows.

**Comment by nikp123** [comment] 2020-06-07 13:46
impressively enough conky has managed to somehow override that behaviour (thanks for that resource, turns out it's really helpful for avoiding this issue)

let me investigate, this might be possible after all

**Comment by nikp123** [comment] 2020-06-07 13:56
nice it works, turns out there's an option for that exact behavior

going to push an update once I clean this up (and do some tests)

**Comment by nikp123** [comment] 2020-06-07 14:19
try the new build, and if it works close the issue

**Comment by nikp123** [comment] 2020-06-07 14:20
Also huge thanks again for linking that resource, I've been looking on how to resolve this issue myself

**Comment by nikp123** [comment] 2020-06-07 15:03
Try now, I've ironed out the issues.

But in order to achieve the same as conky you have to turn on both override_redirect and keep_below

**Comment by xdrie** [comment] 2020-06-07 21:41
thank you so much!

**Comment by xdrie** [comment] 2020-06-07 21:44
I just tested it and it now works as intended (I am using `override_redirect = 1`, `keep_below = 1`, and `interactable = 0`

**Closed** 2020-06-07 21:45 UTC
Labels: behavior, bug, enhancement, feature
