### ISSUE TITLE
Can't get non-transparent window under Kubuntu

### ISSUE THREAD

**Issue by Mitsunee** [nikp123/xava#5] opened 2019-11-03 17:37 UTC
I just freshly built xava from this repo, installed it and now I can't get the window to be non-transparent anymore. It's seemingly completely ignoring the transparency setting in the config file. Gradient mode also appears to work with transparency "off".

I'm using Kubuntu 19.04 currently, xava reports its version as 0.6.2.3.

Example screenshot:
![image](https://user-images.githubusercontent.com/19474909/68089424-e85d6700-fe68-11e9-98c1-95f25b02c514.png)

Expected result: transparency is disabled, background is black with no transparency.

**Comment by nikp123** [comment] 2019-11-04 08:14
can't reproduce the issue, do you mind sending your config file
however i also noticed that opengl + shadows causes something similar to this (but not for the entire window), so that's why the bug label

also am kind of busy at school right now, so updates may not come that fast

**Comment by Mitsunee** [comment] 2019-11-04 11:06
Here's my current config file: https://pastebin.com/KeiFAivc
I've tried toggling window borders, shadows, opengl, transparency, messed around with the colors, `set_win_props`, `foreground_opacity`, but nothing would result in anything but a completely transparent background. The shadows worked fine on the default I had after the installation (I think it partially overrode my existing config file? I don't know if and how many version I skipped)

**Comment by nikp123** [comment] 2019-11-04 11:48
so far it seems that i3wm doesn't have this issue, going to test on Kwin

**Comment by nikp123** [comment] 2019-11-04 11:53
nope, not even Kwin
do you mind sharing your GPU and drivers
also are you under wayland?

**Comment by Mitsunee** [comment] 2019-11-04 11:58
https://pastebin.com/DD96drkn <- output of `nvidia-smi`

**Comment by nikp123** [comment] 2019-11-04 12:02
try undoing this commit: https://github.com/nikp123/xava/commit/9ddfc59c112337bef7979b7f5ff971331a6523ad

seems i've messed with color initialization, so this might be the most plausable source of the problem

**Comment by nikp123** [comment] 2019-11-04 12:08
also copy the line src/graphical_x.c 544 after 519 and try again

I don't have NVIDIA hardware anymore for testing, sorry about that

**Comment by Mitsunee** [comment] 2019-11-04 12:18
Reverting https://github.com/nikp123/xava/commit/9ddfc59c112337bef7979b7f5ff971331a6523ad didn't seem to change anything.

I don't quite understand what you wanted me to copy where? I only have the tiniest bit of experience with C as I usually work with javascript.

**Comment by nikp123** [comment] 2019-11-04 12:25
the source line which is in the file src/output/graphical_x.c at 544,
copy it after the line in the same file in 519 and rebuild

**Comment by nikp123** [comment] 2019-11-04 12:32
try putting ``XSync(xavaXDisplay, 0);`` after line 519 in src/output/graphical_x.c

**Comment by Mitsunee** [comment] 2019-11-04 12:35
line 519 in the current code (right) or with https://github.com/nikp123/xava/commit/9ddfc59c112337bef7979b7f5ff971331a6523ad reverted (left)?
![image](https://user-images.githubusercontent.com/19474909/68121413-ff06cb00-ff07-11e9-83ea-651929f56b70.png)

**Comment by nikp123** [comment] 2019-11-04 12:36
just put that line in the new one

**Comment by Mitsunee** [comment] 2019-11-04 12:40
That does not seem to change it either, but I noticed that the bars seem slightly transparent again, even though that should be disabled by the config file.

**Comment by nikp123** [comment] 2019-11-04 12:42
i know this may sound dumb, but can you boot into nouveau and check if the issue persists

this is just to confirm if its a problem with render contexts that X11 uses

**Comment by Mitsunee** [comment] 2019-11-04 13:12
I couldn't get my system to use nouveau, it completely ignores me choosing it in the System Settings, even after a reboot (tried launching xava anyways, background was still transparent).

**Comment by nikp123** [comment] 2019-11-04 13:21
strange, will look into it if i manage to get hardware to test on.
but for now, you can only use that old version

sorry about that

**Comment by nikp123** [comment] 2019-11-30 13:16
Try to build now,
I've tested this on a 960M

The issue was that XAVA was choosing the wrong color depth

**Comment by Mitsunee** [comment] 2019-12-01 13:17
that was indeed the problem
![image](https://user-images.githubusercontent.com/19474909/69914480-5899e100-1445-11ea-8936-e7b1fe8b71ff.png)

**Comment by nikp123** [comment] 2019-12-01 14:47
Closing, since the fix is confirmed working.

**Closed by nikp123** 2019-12-01 14:47 UTC
Labels: bug
