### ISSUE TITLE
[Feature Request] Multithreading the FFT calculation

### ISSUE THREAD

**Issue by TechAdvancedCyborg** [nikp123/xava#25] opened 2020-10-03 10:36 UTC
I don't know if it is possible, but would it be possible to multithread the whole FFT calculation? Maybe dividing parts of the audio spectrum or buffering frames... My CPU has 28 threads and can easily run XAVA but when I assign 1 bar per pixel it doesn't run at full framerate... I'll have a look myself but I don't know at all how this could work.

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 10:37
This could help: http://www.fftw.org/fftw2_doc/fftw_4.html

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 10:38
This could also help: https://github.com/pkestene/simpleFFTW/tree/master/c

**Comment by nikp123** [comment] 2020-10-03 10:52
I don't think the FFT algorithm is at fault here. As the buffer size doesn't increase with bar count, you have to change ``fft_size`` manually.

First of all: How many bars are we talking about? Because if your CPU runs at least at 2GHz you *(by my measurements at least)* won't get a performance from after like a few hundred bars.

Secondly, yes it can be multithreaded, but that's already causing memory problems since the stack needs to get replicated for every thread. Possibly turn it into a compile-time thing, idk. But that's just a mess, so either one or the other. Windows handles threads many well (16MBs used RAM), Linux not so much (60 MBs used RAM, even without OpenGL) as it stands. However I could be wrong. and something else is causing lots of memory to be used.

Thirdly, while most of the algorithm can be split into threads, monstercat_filter and oddoneout CANNOT be. As the next value is calculated using the older ones in both algos.

I like the idea, I just don't see how it would work without causing more hassle.

**Comment by nikp123** [comment] 2020-10-03 10:55
However, if it's really the FFT algorithm that you're suspicious of when it comes to performance, I already have a fork with STFT, which is supposed to split up the integration process of the operation thus being less demanding. But. be warned, it's extremely inaccurate for now.

**Comment by nikp123** [comment] 2020-10-03 10:57
Since you're running that many bars I suggest you turn off  monstercat_filter as it becomes pretty demanding to run. (set it to 0)

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 13:28
I'm talking about 1080 bars here on a i9-7940x running windows.

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 13:29
and with the monstercat filter off it runs much better >82fps

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 13:31
so maybe multithreading the monstercat smoothing would be a better use of time

**Comment by nikp123** [comment] 2020-10-03 13:45
lol.. the monstercat filter doesnt do shit when I added oddoneout

**Comment by nikp123** [comment] 2020-10-03 13:46
literally looks the same with it on and off

how?

**Comment by nikp123** [comment] 2020-10-03 13:49
Also use ``perf record $executable_name``
and then ``perf analyze`` to see what's the bottleneck

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 13:55
perf on linux right?

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 13:55
I'll do that on the same machine.

**Comment by nikp123** [comment] 2020-10-03 13:55
yes

**Comment by nikp123** [comment] 2020-10-03 13:56
also 10% CPU usage with 800 bars

i dont get it

**Comment by nikp123** [comment] 2020-10-03 13:56
oh
monstercat_filter is bloaty af

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 13:57
k gonna restart the pc to linux
brb

**Comment by nikp123** [comment] 2020-10-03 13:57
![image](https://user-images.githubusercontent.com/4696350/94993418-28edc500-0591-11eb-8f49-ac27144ae4cd.png)
pretty much

**Comment by nikp123** [comment] 2020-10-03 13:59
also the heaviest operation in main is float to int conversion for audio

**Comment by nikp123** [comment] 2020-10-03 14:01
which to be perfectly honest isn't that demanding

note: also the code that checks if the audio is silence is demanding

maybe a loop optimization here?

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:02
yes, also linux-tools doesn't have a version for my kernel

**Comment by nikp123** [comment] 2020-10-03 14:02
wait it's a kernel utility?

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:03
i believe so

**Comment by nikp123** [comment] 2020-10-03 14:05
> i believe so

apt-get install linux-tools-common linux-tools-generic linux-tools-`uname -r`

You need it for your specific kernel

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:05
yup linux-tools-5.8.0-19 doesn't exist tho

**Comment by nikp123** [comment] 2020-10-03 14:06
try linux-tools-5.8.0

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:07
I hadn't used linux for a week and the kernel had upgraded so that's why, the tools are available for the version I'm upgrading to

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:08
5.8.0-19 to 5.8.0-20

**Comment by nikp123** [comment] 2020-10-03 14:09
but yeah, pretty much the issue is ``monstercat_filter`` being demanding

**Comment by nikp123** [comment] 2020-10-03 14:09
when run on like 1000 bars, which is way more than I designed it to do, but sure....

**Comment by nikp123** [comment] 2020-10-03 14:11
also don't forget -DCMAKE_BUILD_TYPE=Debug because well **symbols**

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:11
yup

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:13
```
Error:
Access to performance monitoring and observability operations is limited.
Consider adjusting /proc/sys/kernel/perf_event_paranoid setting to open
access to performance monitoring and observability operations for users
without CAP_PERFMON or CAP_SYS_ADMIN Linux capability.
perf_event_paranoid setting is 4:
  -1: Allow use of (almost) all events by all users
      Ignore mlock limit after perf_event_mlock_kb without CAP_IPC_LOCK
>= 0: Disallow raw and ftrace function tracepoint access
>= 1: Disallow CPU event access
>= 2: Disallow kernel profiling
To make the adjusted perf_event_paranoid setting permanent preserve it
in /etc/sysctl.conf (e.g. kernel.perf_event_paranoid = <setting>)
```

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:14
what should I set it to?

**Comment by nikp123** [comment] 2020-10-03 14:14
``-1`` but do so temporarely

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:15
how do I modify it?

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:15
`sudo nano /proc/sys/kernel/perf_event_paranoid`?

**Comment by nikp123** [comment] 2020-10-03 14:16
no
```sysctl -w kernel.perf_event_paranoid = -1```

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:16
`sudo sysctl -w kernel.perf_event_paranoid=-1` is the answer

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:18
analyze is not a perf command...

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:19
![image](https://user-images.githubusercontent.com/17462236/94993864-2fca0700-0594-11eb-93c3-8c4ef3482f67.png)

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:19
yup monstercat_filter is to blame

**Comment by nikp123** [comment] 2020-10-03 14:20
also... pow isn't meant to be THAT heavy

**Comment by nikp123** [comment] 2020-10-03 14:20
are you sure that the build is optimized... like at ALL

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:20
just a normal cmake build

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:21
also probably due to all the shadows from that many bars

**Comment by nikp123** [comment] 2020-10-03 14:22
hold on, gotta try with opengl now

**Comment by nikp123** [comment] 2020-10-03 14:28
nope
still isn't as demanding as monstercat_filter

**Comment by nikp123** [comment] 2020-10-03 14:28
just a another 30-40% more due to  shadow math, which is complex tbh

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:29
yes, without that many bars pow is exponentially less demanding

**Comment by nikp123** [comment] 2020-10-03 14:29
not that the pow is the problem, but it's running way slower on your machine

**Comment by nikp123** [comment] 2020-10-03 14:30
im gonna ask: Do you even have a FPU, like holy crap?

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:30
FPU?

**Comment by nikp123** [comment] 2020-10-03 14:32
Floating Point Unit, basically a math coprocessor. Existed since the 70s on Intel machines

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:32
lol

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:33
Yeah sooner or later I'm gonna to switch to AMD, Intel is starting to piss me off

**Comment by nikp123** [comment] 2020-10-03 14:34
bruh i have a broadwell potato cpu and even I don't have this issue lol

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:36
lol

**Comment by nikp123** [comment] 2020-10-03 14:36
Recommended Customer Price
$1684.00

oh god

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:37
For the I9-7940x ?

**Comment by nikp123** [comment] 2020-10-03 14:37
Intel® SSE4.1, Intel® SSE4.2, Intel® AVX2, Intel® AVX-512

it does, it's just not enabled

**Comment by nikp123** [comment] 2020-10-03 14:37
yes

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:37
how do I enable it?

**Comment by nikp123** [comment] 2020-10-03 14:37
something is broke in your cmake config

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:38
broke cmake

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:38
how do I fix it?

**Comment by nikp123** [comment] 2020-10-03 14:41
try forcing ```CMAKE_C_FLAGS=-O3```

**Comment by nikp123** [comment] 2020-10-03 14:47
https://stackoverflow.com/questions/41361631/optimize-in-cmake-by-default

there's this, but nothing much

**Comment by nikp123** [comment] 2020-10-03 14:48
also keep an eye out for CMAKE_C_* as well

**Comment by TechAdvancedCyborg** [comment] 2020-10-03 14:52
k

**Comment by TechAdvancedCyborg** [comment] 2020-10-04 09:18
rebuilt XAVA with new CMAKE settings and pow is a bit less demanding...

**Comment by TechAdvancedCyborg** [comment] 2020-10-04 09:19
so yeah a viable option for better performance would probably be slimming down the monstercat_filter function or multithreading it...

**Comment by nikp123** [comment] 2020-10-04 20:18
Can't decide whether or not to just remove monstercat_filter or just disable it... Probably going to do the latter.

**Comment by nikp123** [comment] 2020-10-04 20:19
As for CMAKE, I need to make optimization flags run by default.

**Comment by nikp123** [comment] 2020-11-11 14:02
Closing issue do to having not being relevant anymore

**Closed by nikp123** 2020-11-11 14:02 UTC

**Comment by nikp123** [comment] 2020-11-27 20:26
Also, to add:
Protip: using pipewire with ``pulse`` improves cpu usage by quite a bit
